### ISSUE TITLE
Create Additional Assets

### ISSUE THREAD

**Issue by Alice-Jaffray** [ConorMFinn/CO600-SeriousCyberSec#55] opened 2020-12-29 17:26 UTC
## Expected Behaviour
Assets for the rest of the house:

- [ ] Bookcase
- [ ] Dining table
- [ ] Flower pot
- [ ] Sofa
- [ ] Cardboard box
- [ ] Portrait
- [ ] Server towers

## Actual Behaviour
Assets are missing

**Comment by cailafinn** [comment] 2021-01-04 14:00
Just noticed this seems to be a duplicate of #56

**Closed as completed by cailafinn** 2021-01-04 14:00 UTC
Labels: enhancement
